name: dex
description: A Pokedex.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  palette_generator: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/pokemon/small/
    - assets/images/pokemon/large/
    - assets/data/
  fonts:
    - family: OdibeeSans
      fonts:
        - asset: fonts/OdibeeSans-Regular.ttf
    - family: Questrial
      fonts:
        - asset: fonts/Questrial-Regular.ttf